name: Create Unity Package

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd ./UnityFileDetails/
        echo "Assets/Editor/UnityFileDetails.meta" > metaList
        find Assets/Editor/UnityFileDetails -name \*.meta >> metaList

    - run: mkdir output

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/UnityFileDetails.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: output
        name: UnityFileDetails.unitypackage
